### ISSUE TITLE
❔ Miscellaneous

### ISSUE THREAD

**Issue by rwarnking** [rwarnking/github-importer-test-2#60]
<div align='justify'>This is a collection issue for all types of tasks. Here we will collect tagging ideas that are not yet relevant enough to varant a whole issue.</div>

## Open tasks and potential new issues

- [ ] Rework point and click (input functionality)
- [ ] Revisit _accusation_ (Origin: #24)
- [ ] Revisit _queue_& _dilate time_ (Origin: #25)
- [ ] Revisit _automation_ (Origin: #26)
- [ ] Revisit _choose dialog option_ (Origin: #30)
- [ ] Revisit _reasoning_ (Origin: #32)
- [ ] Revisit _contradiction_ (Origin: #33)
- [ ] Revisit _organize information_ (Origin: #35)
- [ ] Revisit _problem types_ (Origin: #38)
- [ ] Revisit _customization_ (Origin: #41)
- [ ] Revisit _motorskills_ (Origin: #44)
- [ ] Revisit _violence_ (Origin: #46)
- [ ] Revisit _structure_ & _cyclic_ (Origin: #54, #55)
- [ ] Revisit _game over condition_ arcade (Origin: #56), Provide a definition for _goc: death_ that explicitly includes _abstract death/failure_ (rythm game => miss too many notes or similar) or add another goc-leaf that catches this.
- [ ] Revisit _competition_ ([Pokemon](https://en.wikipedia.org/wiki/Pokémon), rise up, herostory (Origin: #43)
- [ ] Revisit pay to win and ingame shops as problem solving technique
- [ ] New Tag: _sidequests_ (Origin: #28)
- [ ] New Tag: _info: distribute_ (Origin: #29)
- [ ] New Tag: _info: lookup_ instead of _predefined notes_ (Origin: #36)
- [ ] New Tag: _level editor_ (@rwarnking)
- [ ] New Tag: _mod support_ (@rwarnking)
- [ ] New Tag: _bonuslevel_ ([Plants vs. Zombies GOTY Edition](https://store.steampowered.com/app/3590/Plants_vs_Zombies_GOTY_Edition/), [Super Meat Boy](https://store.steampowered.com/app/40800/Super_Meat_Boy/)) (Origin: #45) (@rwarnking)
- [ ] New Tag: _sandbox_ (GTA) (Origin: #45) (@rwarnking)
- [ ] New Tag: _arcade_ (Origin: #45) (@ArielMant0)
- [ ] New Tag: _Aussichtspunkte_ (might be part of motivations) (@rwarnking)
- [ ] Rivist: Evaluate overlap of replayability tags and cyclic tag (Origin: #55)
- [ ] Remove: _remember self_ (useless) (Origin: #36)

## Problems

- [ ] can not tag Scribblenauts mechanic (@ArielMant0) (problematic games)
- [ ] gamename Event[0] (@rwarnking) (technical problem)
- [ ] investigate the relationship between problem solving, problem solving technique, mechanics

**Comment by rwarnking** [comment]
## Regarding Multiplayer #31

- Multiplayer could use a tag _trading_? (@HendrikBrueckler)
- _Couch coop_ and _local coop_ should be the same (@HendrikBrueckler)
